# Generated by Django 4.2.4 on 2023-10-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0044_genomeentry_concat_fasta_file_alter_genomeentry_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blast_directory',
            field=models.CharField(default='c:/NCBI/blast-BLAST_VERSION+/bin/', max_length=120, verbose_name='blast_directory'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_e_cutoff',
            field=models.CharField(default='1e-6', max_length=120, verbose_name='first_e_cutoff'),
        ),
    ]
