# Generated by Django 4.2.4 on 2023-10-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0046_genomeentry_blast_results_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genomeentry',
            name='blast_files_dir',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blast_files_dir',
            field=models.CharField(default='D:/blastresults/', max_length=120, verbose_name='blast_files_dir'),
        ),
    ]
