# Generated by Django 4.2.4 on 2023-10-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0047_remove_genomeentry_blast_files_dir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomeentry',
            name='blast_analysis_file',
            field=models.CharField(default='', max_length=120, verbose_name='blast_analysis_file'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blast_analysis_dir',
            field=models.CharField(default='D:/blastanalysis/', max_length=120, verbose_name='blast_analysis_dir'),
        ),
        migrations.AlterField(
            model_name='genomeentry',
            name='blast_results_file',
            field=models.CharField(default='', max_length=120, verbose_name='blast_results_file'),
        ),
    ]
