# Generated by Django 4.2.4 on 2023-10-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0048_genomeentry_blast_analysis_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomeentry',
            name='footprint_size',
            field=models.IntegerField(default=-1, verbose_name='footprint_size'),
        ),
    ]
