# Generated by Django 4.2.4 on 2023-10-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0049_genomeentry_footprint_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(default=-1, verbose_name='end')),
            ],
        ),
        migrations.RemoveField(
            model_name='genomeentry',
            name='dir_files',
        ),
        migrations.AlterField(
            model_name='genomeentry',
            name='concat_fasta_file',
            field=models.CharField(default='', max_length=120, verbose_name='concat_fasta_file'),
        ),
        migrations.DeleteModel(
            name='MyFile',
        ),
        migrations.AddField(
            model_name='genomeentry',
            name='footprints',
            field=models.ManyToManyField(blank=True, to='event.footprint'),
        ),
    ]
