# Generated by Django 4.2.4 on 2023-10-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0050_footprint_remove_genomeentry_dir_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footprint',
            name='end',
            field=models.IntegerField(default=-1, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='start',
            field=models.IntegerField(default=-1, verbose_name='start'),
        ),
    ]
