# Generated by Django 4.2.4 on 2023-10-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0051_footprint_end_alter_footprint_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='footprint',
            name='sequence',
            field=models.CharField(default='', max_length=5000, verbose_name='sequence'),
        ),
    ]
