# Generated by Django 4.2.4 on 2023-10-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0052_footprint_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footprint',
            name='sequence',
            field=models.CharField(default='-1', max_length=5000, verbose_name='sequence'),
        ),
    ]
