# Generated by Django 4.2.4 on 2023-10-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0053_alter_footprint_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomeentry',
            name='analysed_gb_files',
            field=models.CharField(default='D:/analysed_gb_files/', max_length=120, verbose_name='analysed_gb_files'),
        ),
    ]
