# Generated by Django 4.2.4 on 2023-10-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0055_userprofile_analysed_gb_files_dir_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genomeentry',
            name='footprint_size',
        ),
        migrations.AddField(
            model_name='genomeentry',
            name='button_analyse_isok',
            field=models.TextField(default=-1, verbose_name='button_analyse_isok'),
        ),
    ]
