# Generated by Django 4.2.4 on 2023-10-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0056_remove_genomeentry_footprint_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomeentry',
            name='footprint_size',
            field=models.IntegerField(default=-1, verbose_name='footprint_size'),
        ),
    ]
