# Generated by Django 4.2.4 on 2023-10-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0057_genomeentry_footprint_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomeentry',
            name='button_analyse_isok',
            field=models.TextField(default='green', verbose_name='button_analyse_isok'),
        ),
    ]
