# Generated by Django 4.2.4 on 2023-10-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0058_alter_genomeentry_button_analyse_isok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomeentry',
            name='button_analyse_isok',
            field=models.TextField(default='red', verbose_name='button_analyse_isok'),
        ),
    ]
