# Generated by Django 4.2.4 on 2023-10-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0059_alter_genomeentry_button_analyse_isok'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomeentry',
            name='button_prepare_isok',
            field=models.TextField(default='red', verbose_name='button_prepare_isok'),
        ),
    ]
