# Generated by Django 4.2.4 on 2023-10-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0060_genomeentry_button_prepare_isok'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomeentry',
            name='button_blast_isok',
            field=models.TextField(default='red', verbose_name='button_blast_isok'),
        ),
        migrations.AddField(
            model_name='genomeentry',
            name='button_blastanal_isok',
            field=models.TextField(default='red', verbose_name='button_blastanal_isok'),
        ),
        migrations.AddField(
            model_name='genomeentry',
            name='button_footprints_isok',
            field=models.TextField(default='red', verbose_name='button_footprints_isok'),
        ),
    ]
