# Generated by Django 4.2.4 on 2023-10-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0061_genomeentry_button_blast_isok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='work_files_dir',
            field=models.CharField(default='D:/workfiles/', max_length=120, verbose_name='work_files_dir'),
        ),
    ]
