# Generated by Django 4.2.4 on 2023-10-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0065_genomeentry_is_list_csv_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomeentry',
            name='is_frequency_pic',
            field=models.CharField(default='', max_length=120, verbose_name='is_frequency_pic'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_frequency_pic_dir',
            field=models.CharField(default='D:/is_pics/', max_length=120, verbose_name='is_frequency_pic_dir'),
        ),
    ]
