# Generated by Django 4.2.4 on 2023-10-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0066_genomeentry_is_frequency_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_frequency_pic_dir',
            field=models.CharField(default='c:/Users/Eris/Documents/visualAutothink/visapp_proj/static/event/images', max_length=120, verbose_name='is_frequency_pic_dir'),
        ),
    ]
