# Generated by Django 4.2 on 2024-07-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0067_alter_userprofile_is_frequency_pic_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blast_directory',
            field=models.CharField(default='', max_length=120, verbose_name='blast_directory'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_frequency_pic_dir',
            field=models.CharField(default=None, max_length=120, verbose_name='is_frequency_pic_dir'),
        ),
    ]
