# Generated by Django 4.2 on 2024-07-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0068_alter_userprofile_blast_directory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_frequency_pic_dir',
            field=models.CharField(default='c:/Users/Eris/Documents/visualAutothink/visapp_proj/static/event/images/', max_length=120, verbose_name='is_frequency_pic_dir'),
        ),
    ]
